[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "build"
  functions = ""
  environment = { NPM_FLAGS = "--legacy-peer-deps" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

 

