[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  environment = { CI = "false", NPM_FLAGS = "--legacy-peer-deps" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
